name: Android UI Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  android-ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run UI tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86
          profile: Nexus 6
          emulator-boot-timeout: 600
          emulator-port: 5558
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -accel off
          script: |
            adb wait-for-device
            boot_completed=""
            until [ "$boot_completed" = "1" ]; do
              boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
              sleep 5
            done
              ./gradlew connectedDebugAndroidTest
