name: Android UI Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  android-ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run UI tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          emulator-boot-timeout: 600
          emulator-options: -accel off
          script: ./gradlew connectedDebugAndroidTest
