name: Android UI Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

#      - name: Run tests
#        run: ./gradlew clean testDebug

      - name: Run UI tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
#          target: default
#          arch: x86
#          profile: Nexus 6
#          emulator-port: 5555
#          emulator-boot-timeout: 600
#          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -accel off
          script: ./gradlew connectedDebugAndroidTest
