name: Android Instrumented Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  instrumented-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Чекаут кода
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Установка JDK
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Кэш для gradle
      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2

      # 4. Установка Android SDK + запуск эмулятора
      - name: Run UI Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: ./gradlew connectedDebugAndroidTest
          emulator-boot-timeout: 600

