name: Android Instrumented Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  instrumented-tests:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download dependencies & cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4
        with:
          api-level: 33
          build-tools: '33.0.2'
          target: android-33

      # Start emulator + run tests (ReactiveCircus action)
      - name: Run instrumentation tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -noaudio -gpu swiftshader_indirect
          script: |
            ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.example.mytestapp.UiTests
